services:
  keycloak-db:
    image: postgres:17.2
    container_name: sandbox_keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  keycloak-instance-a:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: sandbox_keycloak-instance-a
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://sandbox_keycloak-db:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: secret
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: debug
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
    command: start-dev --features organization
    depends_on:
      - keycloak-db
    ports:
      - "8080:8080"

  keycloak-instance-b:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: sandbox_keycloak-instance-b
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://sandbox_keycloak-db:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: secret
      KC_HOSTNAME: 127.0.0.1
      KC_HOSTNAME_PORT: 8081
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: debug
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
    command: start-dev --features organization
    depends_on:
      - keycloak-db
    ports:
      - "8081:8080"