spring.security.oauth2:
  client:
    provider:
      keycloak:
        issuer-uri: http://localhost:8080/realms/master
  resourceserver:
    jwt:
      issuer-uri: http://localhost:8080/realms/master

server.port: 8090